language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  fast_finish: true

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - composer require --dev "laravel/laravel:^7.0" --no-update
  - composer update

script:
  - phpunit
